import './style.css';
import { jsPDF } from 'jspdf';

const arrow = '↗';
document.querySelector('#app').innerHTML = `
<header><a class="brand" href="./"><span class="brand-icon">A<span>✦</span></span><span>BRIAN'S ACE<span class="brand-sub">SIGN MAKER</span></span></a><div class="header-note"><span class="status-dot"></span> MADE FOR YOUR STORE</div></header>
<main><div class="intro"><div class="eyebrow">A GOOD DEAL DESERVES A GOOD SIGN</div><h1>Big savings.<br>Clear signs.</h1><p>Turn your next promotion into a shelf-ready sale sign.<br>Add the details. Preview it. Print it.</p></div>
<div class="workspace"><section class="editor"><div class="section-heading"><span class="step">01</span><h2>Make it yours</h2></div><p class="section-description">Enter your product and pricing details below.</p>
<form id="details"><label for="product">Product name</label><input id="product" name="product" value="Premium Interior Paint" placeholder="e.g. Premium Interior Paint" maxlength="90" required><label for="item">Ace item number <span>OPTIONAL</span></label><input id="item" name="item" value="1023456" placeholder="e.g. 1023456" maxlength="30"><div class="price-fields"><div><label for="regular">Regular price</label><div class="currency"><span>$</span><input id="regular" name="regular" type="number" min="0.01" max="999999.99" step="0.01" value="39.99" required></div></div><div><label for="sale">Sale price</label><div class="currency"><span>$</span><input id="sale" name="sale" type="number" min="0" max="999999.99" step="0.01" value="29.99" required></div></div></div><p class="error" id="error" aria-live="polite"></p><div class="format"><span class="paper-icon">▤</span><div><strong>Full-page sale sign</strong><small>US Letter · 8.5 × 11 in · Portrait</small></div><span class="check">✓</span></div><button type="submit" class="primary"><span>↓ &nbsp; Download PDF</span><span>${arrow}</span></button><button type="button" class="secondary" id="print">▤ &nbsp; Print sign</button><p class="footnote">Ready to print. No color ink needed.</p></form></section>
<section class="preview-area"><div class="preview-heading"><div class="section-heading"><span class="step">02</span><h2>Your sign, live</h2></div><span class="live"><span class="status-dot"></span> LIVE PREVIEW</span></div><div class="paper-stage"><article class="sign" id="sign"><div class="sign-top"><span>ACE</span><small>THE HELPFUL PLACE.</small></div><div class="sale-banner">SALE</div><div class="sign-body"><h3 id="sign-product"></h3><div class="sign-item" id="sign-item"></div><div class="sale-price"><span>$</span><strong id="sign-dollars"></strong><sup id="sign-cents"></sup></div><div class="regular-line">REG. <span id="sign-regular"></span></div><div class="savings" id="sign-savings"></div></div><div class="sign-bottom">GREAT FINDS. EVEN BETTER PRICES.</div></article></div><div class="preview-caption"><span>↑ &nbsp; Your PDF will look just like this.</span><span>100% BLACK & WHITE</span></div></section></div>
<div class="how"><span class="eyebrow">FROM DETAILS TO DISPLAY</span><div><span>01</span> Add your product</div><span class="flow-arrow">→</span><div><span>02</span> Check your sign</div><span class="flow-arrow">→</span><div><span>03</span> Print & put it up</div></div></main><footer><span>Brian's Ace Sign Maker</span><span>Simple signs. Standout savings.</span></footer>`;
const form = document.querySelector('form');
const money = n => '$' + n.toFixed(2);
function data(){return {product:form.product.value.trim(),item:form.item.value.trim(),regular:Number(form.regular.value),sale:Number(form.sale.value)}}
function update(){const d=data();document.querySelector('#sign-product').textContent=d.product||'Your product name';document.querySelector('#sign-item').textContent=d.item?'ACE ITEM # '+d.item:'';const price=(Number.isFinite(d.sale)?d.sale:0).toFixed(2).split('.');document.querySelector('#sign-dollars').textContent=price[0];document.querySelector('#sign-cents').textContent=price[1];document.querySelector('#sign-regular').textContent=money(d.regular);document.querySelector('#sign-savings').textContent=d.regular>d.sale?'YOU SAVE '+money(d.regular-d.sale):'EVERYDAY VALUE';document.querySelector('#error').textContent='';}
function valid(){if(!form.reportValidity())return false;const d=data();if(!d.product){document.querySelector('#error').textContent='Please enter a product name.';return false;}if(d.sale>=d.regular){document.querySelector('#error').textContent='Sale price must be lower than the regular price.';return false;}return true;}
form.addEventListener('input',update);update();
form.addEventListener('submit',e=>{e.preventDefault();if(!valid())return;const d=data();const pdf=new jsPDF({unit:'in',format:'letter'});pdf.setDrawColor(0);pdf.setLineWidth(.025);pdf.rect(.4,.4,7.7,10.2);pdf.setFont('helvetica','bold');pdf.setFontSize(40);pdf.text('ACE',.7,1.15);pdf.setFontSize(10);pdf.text('THE HELPFUL PLACE.',7.8,1.03,{align:'right'});pdf.setFillColor(0);pdf.rect(.4,1.45,7.7,1.65,'F');pdf.setTextColor(255);pdf.setFontSize(95);pdf.text('SALE',4.25,2.68,{align:'center'});pdf.setTextColor(0);pdf.setFontSize(30);const lines=pdf.splitTextToSize(d.product,6.7);pdf.text(lines,4.25,3.9,{align:'center'});pdf.setFontSize(12);pdf.text(d.item?'ACE ITEM # '+d.item:'',4.25,5.3,{align:'center'});pdf.setFontSize(d.sale>=10000?65:100);pdf.text(money(d.sale),4.25,7.15,{align:'center'});pdf.setFontSize(20);pdf.text('REG. '+money(d.regular),4.25,8.05,{align:'center'});pdf.rect(2.15,8.55,4.2,.6);pdf.setFontSize(18);pdf.text('YOU SAVE '+money(d.regular-d.sale),4.25,8.95,{align:'center'});pdf.line(.4,9.8,8.1,9.8);pdf.setFontSize(12);pdf.text('GREAT FINDS. EVEN BETTER PRICES.',4.25,10.28,{align:'center'});pdf.save((d.product.replace(/[^a-z0-9]+/gi,'-').toLowerCase()||'sale')+'-sign.pdf');});
document.querySelector('#print').addEventListener('click',()=>{if(valid())window.print()});
